defaults:
  - _self_

learned_pag_adj_file: learned_graph_adj.npy
baseline_pag_adj_file: baseline_graph_adj.npy

combined_pag_adj_file: combined_model_pag_adj.npy
combined_pag_plot_file: combined_model_pag.png
dag_vs_combined_metrics_file: dag_vs_combined_pag_metrics.json
data_vs_combined_metrics_file: data_vs_combined_pag_metrics.json
